name: test-all
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v2

      # Pythonの環境をセットアップ
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # pytestをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      # pytest -> JUnit xml形式で結果を出力
      - name: PyTest
        run: |
          ls
          ls ..
          python -m pytest tests --junit-xml results/pytest.xml --cov --cov-branch --cov-report=xml:results/cov.xml
        continue-on-error: true

      # テスト結果の表示
      - name: Upload Pytest Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Pytest Results (Python 3.9)
          path: results/pytest.xml

      - name: Download Artifacts
        if: success() || failure()
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Pytest Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/pytest.xml

